stages:
    - build

build_image:
    tags:
        - docker
    image: ${CI_REGISTRY}/microchip-linux-enclustra:2024.2
    stage: build
    script:
        - kas shell build.yml -c "MACHINE=refdes-${MODULE}-${BASEBOARD} bitbake image-minimal-hwtest"
    parallel:
        matrix:
            - BASEBOARD: ["st1", "pe1", "pe3"]
            - MODULE: ["me-mp1-250-si-d3en", "me-mp1-250-si-d3en-e1"]
    rules:
        - when: manual
    timeout: 1 hours
    artifacts:
        name: build_${MODULE}-${BASEBOARD}_${CI_JOB_ID}
        paths:
            - ./build/tmp-glibc/deploy/images/refdes-${MODULE}-${BASEBOARD}/*.wic
        expire_in: 1 day
