header:
    version: 14

machine: refdes-me-mp1-250-si-d3en-pe1
# machine: refdes-me-mp1-250-si-d3en-pe3
# machine: refdes-me-mp1-250-si-d3en-st1
# machine: refdes-me-mp1-250-si-d3en-e1-pe1
# machine: refdes-me-mp1-250-si-d3en-e1-pe3
# machine: refdes-me-mp1-250-si-d3en-e1-st1

distro: nodistro

target: image-minimal-hwtest

repos:

    bitbake:
        url: "https://git.openembedded.org/bitbake"
        commit: 40fd5f4eef7460ca67f32cfce8e229e67e1ff607
        layers:
            .: excluded

    openembedded-core:
        url: "https://git.openembedded.org/openembedded-core"
        commit: 077aab43f2c928eb8da71934405c62327010f552
        layers:
            meta:

    meta-polarfire-soc-yocto-bsp:
        url: "https://github.com/polarfire-soc/meta-polarfire-soc-yocto-bsp"
        commit: 4bb061e61cc9e9d3889221a0cb4a42d99033ee6d
        layers:
            meta-polarfire-soc-bsp:

    meta-enclustra-mpfs:
        layers:
            meta-enclustra-mpfs:
            meta-enclustra-refdes:

    meta-openembedded:
        url: https://git.openembedded.org/meta-openembedded
        commit: de8681b4a2a101b99dd2c48d89a7de2ccd9a961f
        layers:
            meta-oe:
            meta-python:
            meta-networking:

    meta-security:
        url: https://git.yoctoproject.org/meta-security
        commit: b9cf9cd639bc8d1b4828eb0bd012b71486d35176
        layers:
            meta-tpm:

local_conf_header:
    meta-enclustra-mpfs: |
        PACKAGE_CLASSES ?= "package_ipk"
        PATCHRESOLVE = "noop"
        EXTRA_IMAGE_FEATURES:append = " ssh-server-dropbear"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        require conf/distro/include/no-static-libs.inc
        require conf/distro/include/yocto-uninative.inc
        require conf/distro/include/security_flags.inc
        INHERIT:append = " uninative"
        DISTRO_FEATURES:append = " largefile systemd tpm pam "
        VIRTUAL-RUNTIME_init_manager = "systemd"
