#@TYPE: Machine
#@NAME: me-pe1-generic
#@SOC: Polarfire SoC
#@DESCRIPTION: Machine configuration for the Enclustra MP1 module

MACHINEOVERRIDES =. "${@['', 'me-pe1-generic:']['me-pe1-generic' != '${MACHINE}']}"
