#@TYPE: Machine
#@NAME: me-pe3-generic
#@SOC: Polarfire SoC
#@DESCRIPTION: Machine configuration for the Enclustra MP1 module

MACHINEOVERRIDES =. "${@['', 'me-pe3-generic:']['me-pe3-generic' != '${MACHINE}']}"
