#@TYPE: Machine
#@NAME: me-st1-generic
#@SOC: Polarfire SoC
#@DESCRIPTION: Machine configuration for the Enclustra MP1 module

MACHINEOVERRIDES =. "${@['', 'me-st1-generic:']['me-st1-generic' != '${MACHINE}']}"
