#@TYPE: Machine
#@NAME: me-mp1-generic
#@SOC: Polarfire SoC
#@DESCRIPTION: Machine configuration for the Enclustra MP1 module

MACHINEOVERRIDES =. "${@['', 'me-mp1-generic:']['me-mp1-generic' !='${MACHINE}']}"

require conf/machine/include/riscv/tune-riscv.inc

MACHINE_FEATURES = "keyboard ext2 serial usbgadget usbhost"
MACHINE_TYPE = "smp"

KERNEL_CLASSES = "kernel-fitimage"
KERNEL_IMAGETYPE = "fitImage"
EXTERNAL_KERNEL_DEVICETREE ?= "devicetree/enclustra_mercury_mp1.dtb"

PREFERRED_PROVIDER_virtual/kernel ?= "mpfs-linux"
PREFERRED_PROVIDER_virtual/dtb ?= "device-tree"

PREFERRED_VERSION_openocd-native = "riscv"
PREFERRED_VERSION_openocd = "riscv"

UBOOT_MACHINE="enclustra_mercury_mp1_defconfig"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-mchp"
UBOOT_DEVICE_TREE ?= "enclustra_mercury_mp1.dtb"
UBOOT_ENTRYPOINT = "0x84200000"
UBOOT_DTB_LOADADDRESS = "0x86200000"

HSS_PAYLOAD = "uboot"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " kernel-modules"

IMAGE_FSTYPES += "ext4"
